sudo: false

branches:
  except:
    - gh-pages

notifications:
  email: false

matrix:
  include:
    - language: android
      name: "Android"
      jdk: oraclejdk8
      env:
        - secure: "SWQBLsaI5fOfiM+48/oAOcynsnpa1hHADxs8Vsmt7gsqVrtL369znwsX+PkNOXTdAROPKHzfCw1PkMSKiWHwSB+Gc8fMqFoVjxPnpi0NAhm2b4q4pq6GLOed2xF93eLoQZ7x4UwcUie58Qlwif9ZSGyp+7V6fEy7/AexGLPAuD0="
        - secure: "gFmZ18DktyZonExeAYGT4HtCodvAbRcH94AImWG6DrJZFzGkRSN//s1AjrgkAL/jZ4lLuoxyCs1nBoX2U83LmpJ8KxLIhU/45JlJgmD1tnE2zdFim6dHN+J6Yj7MCWqD5KO6E0dJickTJG2XzFu0oN3vBn7sETliQHzlw2lw8ME="
      licenses:
        - 'android-sdk-license-.+'
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.m2
    - language: swift
      name: "Swift - Cocoapods (Xcode 10.1)"
      os: osx
      osx_image: xcode10.1
      before_install:
        - gem update --system
        - gem install bundler
      script:
        - bundle exec pod repo update
        - bundle exec pod lib lint Workflow.podspec --allow-warnings
    - language: swift
      name: "Swift - SPM (Xcode 10.1)"
      os: osx
      osx_image: xcode10.1
      cache:
        directories:
          - .build
      before_install:
        - gem update --system
        - gem install bundler
        - swift --version
        - swift build --verbose
      script:
        - swift test
    - language: node_js
      name: "Documentation"
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      script:
        - cd docs
        - yarn install
        - yarn test
        - yarn build --prefix-paths
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs/public
        target-branch: gh-pages
        on:
          branch: master
